### ISSUE TITLE
Error on reconstruct.py line 71? Python3

### ISSUE THREAD

**Issue by sfeister** [flash-center/PRaLine#5]
When I try to follow the lin-reconstruct example from Anaconda3 in Windows10, I get this error:
```
(C:\ProgramData\Anaconda3) C:\Users\scott\Documents\Python Scripts\2017-11-21_praline_test>lin-reconstruct test_input.txt
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\lin-reconstruct-script.py", line 11, in <module>
    load_entry_point('praline==0.0.5', 'console_scripts', 'lin-reconstruct')()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2751, in load_entry_point
    return ep.load()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2405, in load
    return self.resolve()
  File "C:\ProgramData\Anaconda3\lib\site-packages\pkg_resources\__init__.py", line 2411, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\ProgramData\Anaconda3\lib\site-packages\praline\__init__.py", line 5, in <module>
    from . import reconstruct
  File "C:\ProgramData\Anaconda3\lib\site-packages\praline\reconstruct.py", line 71
    print "...done.  " + buf
                     ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(int "...done.  " + buf)?
```

**Comment by sfeister** [comment]
Tested and this issue is resolved
